alessandrofama/wwise-godot-integration

wwise-gdnative/src/wwise_utils.h
This checks if exported banks already exist in the user directory and only copies new or modified files. Fixes https://github.com/alessandrofama/wwise-godot-integration/issues/8
=> Checking for existing banks in user directory and skipping identical files

wwise-gdnative/gdnative-demo/wwise/wwise_settings.gd, wwise-gdnative/src/wwise_gdnative.cpp
This simple change adds a checkbox to the common Wwise project settings to automatically load the init bank at engine startup.
=> Added option to load init bank at startup to Project Settings

wwise-gdnative/gdnative-demo/demo-scenes/misc/callbacks_test_ak_event.tscn, wwise-gdnative/gdnative-demo/demo-scenes/nodes/2d/callbacks_demo_ak_event_2d.tscn, wwise-gdnative/gdnative-demo/scripts/misc/callbacks_ak_event_2d_demo.gd, wwise-gdnative/gdnative-demo/scripts/misc/callbacks_ak_event_demo.gd, wwise-gdnative/gdnative-demo/wwise/runtime/helpers/ak_game_obj.gd, wwise-gdnative/gdnative-demo/wwise/runtime/helpers/ak_game_obj_2d.gd, wwise-gdnative/gdnative-demo/wwise/runtime/nodes/ak_event.gd, wwise-gdnative/gdnative-demo/wwise/runtime/nodes/ak_event_2d.gd
This change adds event callback signals to AkEvent and AkEvent2D nodes. It aims at simplify the process of setting up callbacks for these two custom nodes.
Main changes:
- AkEvent and AkEvent2D nodes now display selectable checkboxes instead of an enum export. This allows the user to select multiple callbacks:
- Node/Signals tab of the AkEvent and AkEvent2D nodes now display the signals that can be connected to other nodes:
If the connected nodes have a script attached, corresponding functions will be automatically created:
- Moved exported properties of the AkEvent and AkEvent2D nodes to the "parent" ak_game_obj and ak_game_obj_2d scripts to clear things up and make the custom AkEvent nodes more readable.
=> Add callback signals to AkEvent and AkEvent2D nodes

wwise-gdnative/Android.mk, wwise-gdnative/src/wwise_gdnative.cpp, wwise-gdnative/src/wwise_gdnative.h, wwise-gdnative/src/wwise_godot_io.cpp, wwise-gdnative/src/wwise_godot_io.h, wwise-gdnative/src/wwise_utils.h
This PR replaces the default blocking I/O implementation with a custom blocking I/O implementation.
Wwise’ default blocking I/O implementation expects banks that can be opened with platform ``fopen`` methods. This works fine while working in-editor, but in exported builds files are packaged in a virtual file system that is inaccessible to Wwise. Our current workaround for this problem is copying the banks to the user data folder at the start of the engine and reading the files from there. Location of the banks need to mapped for different platforms at initialization, which can be error-prone.
This custom blocking I/O implementation uses Godot’s ``File`` class to open and read .bnk and .wem files, bypassing the need for the workaround mentioned above. Setting the `base path` of the banks …
=> Add custom blocking I/O implementation

wwise-gdnative/gdnative-demo/demo-scenes/misc/callbacks_test_ak_event.tscn, wwise-gdnative/gdnative-demo/demo-scenes/misc/load_bank_async.tscn, wwise-gdnative/gdnative-demo/scripts/3d/callbacks_test.gd, wwise-gdnative/gdnative-demo/scripts/misc/callbacks_ak_event_demo.gd, wwise-gdnative/gdnative-demo/scripts/misc/load_bank_async_test.gd, wwise-gdnative/gdnative-demo/wwise/runtime/helpers/ak_game_obj.gd, wwise-gdnative/gdnative-demo/wwise/runtime/nodes/ak_event.gd, wwise-gdnative/gdnative-demo/wwise/wwise_settings.gd, wwise-gdnative/src/wwise_gdnative.cpp, wwise-gdnative/src/wwise_gdnative.h, wwise-gdnative/src/wwise_utils.h
This PR aims to simplify the usage of Wwise callbacks in Godot. It removes the signal processing for callbacks from the C++ codebase and implements FuncRefs as callbacks cookies.
With [FuncRefs](https://docs.godotengine.org/en/stable/classes/class_funcref.html) we can create a reference to a function in a given object and pass the reference around, i.e. in this implementation as a cookie to the respective Wwise callbacks. We then can call the referenced function directly from the Wwise callbacks, bypassing the signal processing in ``_process()``.
``post_event_callback``, ``post_event_id_callback``, ``load_bank_async``, ``load_bank_async_id``, ``unload_bank_async`` and ``unload_bank_async_id`` now require an ``Object`` argument, which should be a ``FuncRef`` created in GDScript.
Event …
=> Simplify Callbacks creation and processing by using Godot's FuncRef

.github/workflows/osx_builds.yml, waapiclient-gdnative/README.md, waapiclient-gdnative/SConstruct, wwise-gdnative/README.md, wwise-gdnative/SConstruct, wwise-gdnative/src/wwise_gdnative.h
PR adds support for the arm64 architecture on macOS. SCons will build an universal library that targets both x86_64 and arm64 by default. Godot picks the right one under the hood. Specifying just one architecture is still possibile by passing the `macos_arch` parameter to SCons. Fixes https://github.com/alessandrofama/wwise-godot-integration/issues/43 .
=> Add support for arm64 architecture (Apple M1)

.github/workflows/linux_builds.yml
> Linux binaries usually won't run on distributions that are older than the distribution they were built on. If you wish to distribute binaries that work on most distributions, you should build them on an old distribution such as Ubuntu 16.04. You can use a virtual machine or a container to set up a suitable build environment.
https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#building-export-templates
By building on a 20.04 host, libWwiseGDNative.so has a dependency on some math (libm) symbols at glibc version 2.29 (Ubuntu 20.04's version).
```
$ readelf -s release/libWwiseGDNative.so | grep "2\.29"
13: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND exp@GLIBC_2.29 (10)
18: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND log@GLIBC_2.29 (10)
38: …
```
=> Change linux build host to ubuntu 18.04

.github/workflows/build_all.yml, addons/Wwise/native/SConstruct
To mitigate potential issues arising from the dependency on MSVCP140 and VCRUNTIME140, which may not be present on all Windows systems, this change adopts the use of static CRT (C Runtime Library) versions for the Wwise libraries. The godot-cpp library will also statically link the runtime libraries on Windows.
=> Switch to static CRT library versions for Windows

addons/Wwise/native/src/wwise_gdextension.cpp
An incompatibility between the load_init_bank_at_startup setting and the use_soundbank_names setting was identified. When load_init_bank_at_startup was enabled, the integration attempted to load the Init bank using its ID, conflicting with the use_soundbank_names setting. This PR fixes this issue.
=> Fix load_init_bank_at_startup compatibility Issue with use_soundbank_names setting

addons/Wwise/native/src/editor/inspector_plugin/ak_inspector_plugin.cpp, addons/Wwise/native/src/editor/waapi_picker/waapi_picker.cpp, addons/Wwise/native/src/editor/waapi_picker/waapi_picker.h
An issue arose where Wwise IDs were not updating correctly in the custom nodes browser due to Godot's resource reloading and cache system. To rectify this problem, the commit enforces the resave of the script resource, ensuring the accurate updating of IDs and resolving the issue effectively.
=> Fix Wwise IDs refresh bug after IDs Generation

addons/Wwise/native/src/wwise_gdextension.cpp
Audio was previously flipped when using the camera 2d node in its default settings.
=> Fix inverted set_2d_position up vector

addons/Wwise/native/src/editor/waapi_picker/waapi_picker.cpp, addons/Wwise/native/src/wwise_settings.cpp
I'm currently playing around with the Wwise Godot Integration and noticed that the port to establish a connection with the Waapi Picker must be 8080. I exposed it to be a setting that can be editied to match the Wamp Port in Wwise.
=> Expose Waapi Port in the Integration Settings

addons/Wwise/native/doc/Wwise.xml, addons/Wwise/native/src/wwise_gdextension.cpp, addons/Wwise/native/src/wwise_gdextension.h
I recently used your implementation of Wwise in Godot for [a game jam](https://snoopy20111.itch.io/objects-in-mirror), and noticed there was no support for Distance Probes, such that 3rd person audio was sometimes a little funky. The Wwise API docs made it look pretty straightforward, so I added it myself by essentially copying the existing code for Register Listener and Register Game Object.
From my personal testing this works as expected, but I'm not deeply familiar with the Wwise API or programming for production use, so I've probably missed some error checking somewhere and haven't run any of the presumably standard tests/analysis. Additionally, I couldn't figure out how to easily get the current Listener Game Object, so I wasn't able to make custom nodes that would act as distance …
=> Add Support for Distance Probes

addons/Wwise/native/doc/Wwise.xml, addons/Wwise/native/src/wwise_gdextension.cpp
This PR refactors the `set_game_object_output_bus_volume` function in `wwise_gdextension.cpp`, enabling the use of `AK_INVALID_GAME_OBJECT` (null in GDScript) as a parameter. Fixes #96.
=> Refactor `set_game_object_output_bus_volume` to allow for `AK_INVALID_GAME_OBJECT` (null) parameter

addons/Wwise/native/src/editor/waapi_picker/waapi_picker.cpp
When users enable the optional inferred declaration warnings in Godot, several warnings appear for the untyped generated Wwise IDs. This can be fixed by explicitly specifying the respective int and dictionary types for the IDs.
=> Fix inferred declaration warnings for generated Wwise IDs

.github/workflows/build_all.yml
macos-11 was removed in April.
=> Update macOS runner to macos-13

addons/Wwise/tests/ak_test_framework.gd, addons/Wwise/tests/test_wwise.gd
This PR updates the test framework in the project to work correctly:
- Bank loading methods need to use the string version of the functions due to the "Use Soundbank names" option in the Wwise-Godot settings being enabled by default.
- The CookieWrapper object actually needs to persist during the tests. It cannot be a local variable.
- `test_get_rtpc_value` was failing (1 frame waiting was not enough).
=> Fix failing tests (Bank loading, cookie wrapper crash, get rtpc value)

addons/Wwise/native/src/scene/ak_geometry.cpp
The current code 
- effectively [places all geometry_instances on global (0, 0, 0)](https://github.com/alessandrofama/wwise-godot-integration/blob/main/addons/Wwise/native/src/scene/ak_geometry.cpp#L136)
- (0, 0, 0) because AkGeometry needs to be child of MeshInstance3D, with AkGeometry most likely having position (0, 0, 0) and MeshInstance3D and its parents having whatever random positions
- places the vertices/triangles of the AkGeometry [according the global transform of the vertices themselves](https://github.com/alessandrofama/wwise-godot-integration/blob/main/addons/Wwise/native/src/scene/ak_geometry.cpp#L109)
When inspected in Wwise Game Object 3D Viewer the diffraction edges/shapes look ok, as the diffraction shapes are placed at the correct world position, just with the …
=> Fixed ak_geometry transform setting in set_geometry

addons/Wwise/native/src/scene/ak_event.cpp, addons/Wwise/native/src/scene/ak_event.h, addons/Wwise/native/src/scene/ak_listener.cpp, addons/Wwise/native/src/scene/ak_listener.h, addons/Wwise/native/src/scene/ak_room.cpp, addons/Wwise/native/src/scene/ak_room.h
Hi Alessandro,
This is the fix for the enter/exit room bug. Prior to this fix, sound would drop out as we changed rooms because after the player entered the new room, it would call _on_area_exited() on the old room, which would set the player's room ID to INVALID_ROOM_ID.
To fix this problems we make two substantive code changes:
1. When the player enters a new room, have the method _on_area_entered() set the player's room ID to the room they are in. If a player goes outside, then _on_area_entered() is not called because outdoors is not a room.
2. When the player exits a room compare the room the player is in with that they're exiting. If they are the same (because the player has not entered another room) it means the player is going outside and we set the room ID to INVALID_ROOM_ID.
I've …
=> Fix enter/exit room bug

addons/Wwise/native/src/scene/ak_event.cpp, addons/Wwise/native/src/scene/ak_event.h, addons/Wwise/native/src/scene/ak_listener.cpp, addons/Wwise/native/src/scene/ak_listener.h, addons/Wwise/native/src/scene/ak_room.cpp
1) We need to use Object::cast_to instead of static_cast in GDExtension
2) Object::get_instance_id is a uint64_t, so the room id in the AkEvent3D and AkListener3D needs to be the same
=> Fix AkRoom not detecting moving between rooms

addons/Wwise/native/src/scene/ak_portal.cpp
It turns out NodePath::is_empty will actually return true for NodePaths assigned in the Editor. This caused a crash when using Portals.
=> Fix crashed caused by AkPortal NodePath references

addons/Wwise/native/SConstruct
'_' is not supported. Fixes #101
=> Replace unsupported character in CFBundleIdentifier for AppStore submission

addons/Wwise/native/src/scene/ak_geometry.cpp
Previously, AkGeometry only supported built-in shapes in MeshInstance3D. This fix makes it possible to consider processing imported meshes.
=> Enable support for ArrayMeshes in AkGeometry

addons/Wwise/native/src/core/wwise_gdextension.cpp, addons/Wwise/native/src/core/wwise_gdextension.h, addons/Wwise/native/src/editor/ak_inspector_plugin.cpp, addons/Wwise/native/src/editor/ak_inspector_plugin.h, addons/Wwise/native/src/editor/ak_waapi_picker.cpp, addons/Wwise/native/src/scene/ak_geometry.cpp, addons/Wwise/native/src/scene/ak_geometry.h, addons/Wwise/tools/wwise_ids.template
- Integrated Acoustic Texture support into the AkGeometry node, allowing to select an Acoustic Texture for the entire mesh surface via a new acoustic_texture property.
- Updated the ID generator to include Acoustic Textures in the Wwise ID generation workflow.
- Exposed the transmission loss value as a new property in AkGeometry.
- Updated relevant editor plugins, including the WAAPI picker and inspector, to handle Acoustic Textures and provide appropriate labels and search options.
Using Acoustic Textures will require regenerating the Wwise IDs in the WAAPI Picker.
=> Add Acoustic Texture Support for AkGeometry

addons/Wwise/native/src/core/wwise_gdextension.cpp, addons/Wwise/native/src/scene/ak_geometry.cpp, addons/Wwise/native/src/scene/ak_geometry.h
This commit addresses issues with geometry reflections, primarily caused by discrepancies between right-handed (Godot) and left-handed (Wwise) coordinate systems.
- Corrected the orientation setup in Wwise::set_geometry_instance to align with the left-handed coordinate system used by Wwise.
- Fixed scaling conversion to ensure proper geometry transformations.
- Adjusted the Z-axis inversion for vertices in AkGeometry::set_geometry, ensuring compatibility with Wwise's coordinate system.
- Corrected triangle indexing to maintain the correct winding order.
- Removed the unused add_indices function from ak_geometry.h and its implementation in ak_geometry.cpp.
=> Fix AkGeometry reflections and right-handed to left-handed Transform conversion

.github/workflows/build_all.yml, addons/Wwise/native/SConstruct, addons/Wwise/native/android/plugin/build.gradle.kts, addons/Wwise/native/src/core/utils.h, addons/Wwise/native/src/core/wwise_gdextension.cpp, addons/Wwise/native/src/core/wwise_gdextension.h, addons/Wwise/native/src/core/wwise_io_hook.cpp, addons/Wwise/native/src/core/wwise_io_hook.h, addons/Wwise/native/src/core/wwise_settings.cpp, addons/Wwise/native/src/core/wwise_settings.h, addons/Wwise/native/src/scene/ak_geometry.cpp, addons/Wwise/native/src/scene/ak_geometry.h, addons/Wwise/native/wwise.gdextension
Initial support for compiling with 24.1 SDK. Workflow improvement will be added in a follow-up PR.
- Updated Godot dependency from 4.2.0 to 4.3.0.
- Adjusted library paths for various platforms, support new toolchains.
- Removed deprecated `AK_ACP_Error` error.
- Removed deprecated `associated_room` parameter in `Wwise::set_geometry_instance`.
- Introduced additional spatial audio settings.
- Added `max_system_audio_objects` support for Windows advanced settings.
- Removed `WwiseIOHook::BatchCancel`.
=> Update Wwise Integration to 24.1

addons/Wwise/native/src/core/types/wwise_event.cpp, addons/Wwise/native/src/core/types/wwise_event.h, addons/Wwise/native/src/scene/ak_event.cpp, addons/Wwise/native/src/scene/ak_event.h
The `AkEvent` nodes should get the current `AkPlayingID` directly from the exposed `WwiseEvent` object.
=> Remove `playing_id` property from `AkEvent` nodes

addons/Wwise/native/src/editor/ak_wwise_inspector_picker.cpp
Fixed an issue with the Wwise picker positioning. Previously, the `popup_on_parent` method caused the picker to open with an unintended Y-axis shift due to position offsets being saved and retrieved incorrectly.
This update replaces `popup_on_parent` with the `popup` method, ensuring the picker opens at the correct position.
=> Fix Wwise Picker positioning

addons/Wwise/native/src/core/wwise_gdextension.cpp
- Fix small typo (WwiseGidot).
- Early return when passing invalid `game_object` to `set_geometry`.
- Print actual `game_object` name in logging functions; Useful for users.
=> Improve `Wwise::set_geometry` logging

.github/workflows/build_all.yml
Previous versions of these actions have been deprecated and need to be updated.
=> Upgrade upload-artifact & download-artifact to v4

.github/workflows/build_all.yml, addons/Wwise/native/SConstruct, addons/Wwise/native/linux/symbols-extension.map
This fixes a crash that occurs when the extension is used alongside other extensions. Same issue that was experienced 
in this project: https://github.com/godotengine/webrtc-native/issues/127
=> Only export extension init symbol on Linux

addons/Wwise/native/src/scene/ak_room.cpp
Fixes a crash when reparenting the AkRoom node.
=> Disconnect Area Signals in AkRoom node

addons/Wwise/native/doc_classes/Wwise.xml, addons/Wwise/native/src/core/utils.h, addons/Wwise/native/src/core/wwise_gdextension.cpp, addons/Wwise/native/src/core/wwise_gdextension.h, addons/Wwise/native/src/scene/ak_listener.cpp, addons/Wwise/native/src/scene/ak_listener.h, tests/GodotProject/test/test_wwise.gd
- Exposed new `is_default_listener` flag for `AkListener` nodes.
- Implemented new APIs in `Wwise` interface: add_listener, remove_listener, add_default_listener, remove_default_listener.
- Refactored single-listener version of `Wwise::set_listeners` and deprecated `Wwise::register_listener`
- Cleaned up listener registration logic in _enter_tree() / _exit_tree() in `AkListener` nodes.
- Updated documentation. (Unfortunately automatic documentation generation by following the guide here: https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_docs_system.html changed formatting for the whole Wwise interface). It shouldn't happen next time.
Closes #149.
=> Enable default and multi-listener support

addons/Wwise/native/src/core/wwise_settings.cpp
Increased the default monitor queue pool size to fix an issue where geometry was not visible in the Game Object 3D Viewer.
=> Increase monitor queue pool size

addons/Wwise/native/src/core/types/wwise_aux_bus.cpp
Use ID version of `PrepareBus`, equivalent to the usage in the `WwiseEvent` Wwise-Type.
Closes #148.
=> Fix PrepareBus on macOS

.github/workflows/build_all.yml
Updated the 'upload-addon' step in the GitHub Actions workflow to run on ubuntu-22.04 instead of the deprecated ubuntu-20.04.
=> Update upload-addon step to ubuntu-22.04

addons/Wwise/native/src/scene/ak_listener.cpp
The calls to `soundengine->unregister_game_obj(this)` in both `AkListener2D::_exit_tree()` and `AkListener3D::_exit_tree()` have been removed. These unregistration steps are handled by the `AkGameObject` helper nodes, making the explicit calls unnecessary.
=> Remove redundant game object unregistration from `AkListener::_exit_tree`

addons/Wwise/native/src/core/wwise_settings.cpp, addons/Wwise/native/src/core/wwise_settings.h
This was not supported and was previously undocumented. In Godot 4.5, setting the `usage` of a setting prints several warnings in the output console every time a project is launched. This PR fixes the issue.
=> Remove `usage` information from ProjectSettings::add_property_info

addons/Wwise/native/src/core/utils.h, addons/Wwise/native/src/core/wwise_gdextension.cpp, addons/Wwise/native/src/core/wwise_gdextension.h
Refactors the Godot-to-Wwise coordinate conversion logic to properly support double-precision Godot builds and enable large world coordinates for game objects.
=> Add support for large world coordinates
